### ISSUE TITLE
README missing from installation tarball

### ISSUE THREAD

**Issue by mrts** [yamatt/python3-chardiff#2]
Installation fails currently with `FileNotFoundError: [Errno 2] No such file or directory: 'README.md'`:

```
$ pip3 install --user chardiff
Collecting chardiff
  Downloading https://files.pythonhosted.org/packages/3b/2a/2bb0f42934f18bfc00fd184a850c59021f3e357f0b270de6f597995a4679/chardiff-1.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u5wp9cqv/chardiff/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u5wp9cqv/chardiff/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-u5wp9cqv/chardiff/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u5wp9cqv/chardiff/setup.py", line 9, in <module>
        long_description=open("README.md").read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

This is because [setup.py](https://github.com/yamatt/python3-chardiff/blob/master/setup.py#L9) tries to read `README.md`
```py
long_description=open("README.md").read(),
```
but it is not included in installation tarball.

Thanks for `chardiff`, helped me to debug a problem in a long string :slightly_smiling_face: just now!

**Comment by yamatt** [comment]
Awesome. Thanks. I'll look in to both of these

**Comment by yamatt** [comment]
Right now. I'm a bit confused as to why the `README.md` is not included in the tarball. I'm going to look in to it in the next couple hours

**Comment by yamatt** [comment]
Way too keen GitHub!

**Comment by yamatt** [comment]
Right. Fixed in 1.0.1. Let me know if this works for you.

I'm glad it was able to help you out.

**Comment by mrts** [comment]
1.0.1 works well, #1 is fixed too - thanks for looking into this :slightly_smiling_face:!

**Comment by yamatt** [comment]
Glad it's fixed! Thanks for reporting :+1:
